language: r
cache: packages
r_packages:
  - EML
  - stringr
  - lubridate
  - covr
  - httr
  - stringi
  - reader
  - readr
  - xml2
  - XML
warnings_are_errors: false
addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - librdf0-dev
      - libv8-dev
      - libjq-dev
      - libudunits2-dev
after_success:
  - Rscript -e 'library(covr); codecov()'
